Make firstboot start doing useful work.
Updating keys, database, and installing packages.

diff --git a/platforms/gce/firstboot b/platforms/gce/firstboot
--- a/platforms/gce/firstboot
+++ b/platforms/gce/firstboot
@@ -1,28 +1,29 @@
 #!/bin/bash
+# Ambroix for GCE
+# Started on the first boot of the machine, as root.
 
-output="/tmp/firstboot-output"
-source_repository="REPO" # To be substituted on imaging
+# Collect plugins
+f=common/kvpf.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }
 
-echo "Hi! I'm running as $(whoami) on $(hostname)." >> $output
+f=platforms/gce/helpers.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }
 
-# Get source data from human
-promptfile=$(mktemp)
-cat <<EOF > $promptfile
-PROMPTFILE_CONTENTS
-EOF
+# Run update.
+pacman-key --refresh-keys
+pacman -Syyu --noconfirm
 
 
-# Install git
-pacman --noconfirm -Syy git || {
-  echo "Could not install git!" >> $output
-  exit 1
-}
+# Set locale settings
+# Ignore time zone; we run in UTC
+ln -s /usr/share/zoneinfo/UTC /etc/localtime
+sed -i 's/^#en_US/en_US/' /etc/locale.gen && locale-gen
+echo LANG=en_US > /etc/locale.conf
 
-{
-  pushd /tmp && \
-    git clone http://${source_repository} -o distro \
-    && popd 
-} || {
-  echo "Could not clone repository ${source_repository}!" >> $output
-  exit 2 
-}
+# Grab packages from the standard list.
+for f in $(ls common/pkgs)
+do
+  cat common/pkgs/$f | xargs pacman -S --noconfirm || {
+    ret=$?
+    echo "Could not install packages!"
+    return $ret
+  }
+done
