Work on making POSIX-compliant

diff --git a/platforms/gce/firstboot b/platforms/gce/firstboot
--- a/platforms/gce/firstboot
+++ b/platforms/gce/firstboot
@@ -1,11 +1,11 @@
-#!/bin/bash
+#!/bin/sh
 # Ambroix for GCE
 # Started on the first boot of the machine, as root.
 
 # Collect plugins
-f=common/kvpf.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }
+f=common/kvpf.fn.sh; . $f || { >&2 echo "$f not found!" && exit 2; }
 
-f=platforms/gce/helpers.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }
+f=platforms/gce/helpers.fn.sh; . $f || { >&2 echo "$f not found!" && exit 2; }
 
 # Run update.
 pacman-key --refresh-keys
@@ -32,6 +32,8 @@ ln -s /usr/share/zoneinfo/UTC /etc/localtime
 sed -i 's/^#en_US/en_US/' /etc/locale.gen && locale-gen
 echo LANG=en_US > /etc/locale.conf
 
+
+
 # Last step:remove this script from startup,
-# gcloud compute instances remove-metadata $(hostname) --keys startup-script
+gcloud compute instances remove-metadata $(hostname) --keys startup-script
 # TODO: Remove its permission after the fact.
diff --git a/platforms/gce/prompt b/platforms/gce/prompt
--- a/platforms/gce/prompt
+++ b/platforms/gce/prompt
@@ -1,15 +1,15 @@
-#!/bin/bash -i
+#!/bin/sh -i
 # Ambroix for GCE
 # Prompt for local and remote settings.
 
 # Collect plugins
-f=common/depend.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }
-f=common/yesno.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }
-f=common/kvpf.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }
-f=common/prompt.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }
-f=common/err.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }
+f=common/depend.fn.sh; . $f || { >&2 echo "$f not found!" && exit 2; }
+f=common/yesno.fn.sh; . $f || { >&2 echo "$f not found!" && exit 2; }
+f=common/kvpf.fn.sh; . $f || { >&2 echo "$f not found!" && exit 2; }
+f=common/prompt.fn.sh; . $f || { >&2 echo "$f not found!" && exit 2; }
+f=common/err.fn.sh; . $f || { >&2 echo "$f not found!" && exit 2; }
 
-f=platforms/gce/helpers.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }
+f=platforms/gce/helpers.fn.sh; . $f || { >&2 echo "$f not found!" && exit 2; }
 
 # TODO: Recover and verify information from an existing promptfile.
 
diff --git a/platforms/gce/verify b/platforms/gce/verify
--- a/platforms/gce/verify
+++ b/platforms/gce/verify
@@ -1,12 +1,12 @@
-#!/bin/bash -i
+#!/bin/sh -i
 # Ambroix for GCE
 # Verify / establish a sane environment for deploying a GCE instance.
 PLATFORM='gce'
 
 echo "Checking sane host environment for platform '$PLATFORM'..."
 
-f=common/depend.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }
-f=common/err.fn.sh; source $f || { >&2 echo "$f not found!" && exit 2; }
+f=common/depend.fn.sh; . $f || { >&2 echo "$f not found!" && exit 2; }
+f=common/err.fn.sh; . $f || { >&2 echo "$f not found!" && exit 2; }
 
 # Test gcloud command
 depend gcloud || {
