More drafting of firstboot script.

diff --git a/platforms/gce/firstboot b/platforms/gce/firstboot
--- a/platforms/gce/firstboot
+++ b/platforms/gce/firstboot
@@ -1,3 +1,33 @@
 #!/bin/bash
 
-echo "Hi! I'm running as $USER on $(hostname)" > /tmp/checkin
+output="/tmp/firstboot-output"
+source_repository="REPO" # To be substituted on imaging
+
+# Get source data from human
+promptfile=$(mktemp)
+echo <<EOF >$promptfile
+PROMPTFILE_CONTENTS
+EOF
+
+
+# Install git
+pacman --noconfirm -Syy git || {
+  echo "Could not install git!" > $output
+  exit 1
+}
+
+{
+  pushd /tmp && \
+    git clone http://${source_repository} -o distro \
+    && popd 
+} || {
+  echo "Could not clone repository ${source_repository}!" > $output
+  exit 2 
+}
+
+{
+  # TODO trigger platform- and user-specific startup scripts, for firstboot and firstlogin.
+}
+
+
+echo "Hi! I'm running as $USER on $(hostname)." > /tmp/checkin
